# Use root/example as user/password credentials
version: "3.1"

services:
  product-service:
    build:
      context: ../product-service/src/
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ProductDatabase__ConnectionString=mongodb://root:example@mongo:27017/
    ports:
      - "8080:80"
      - "8081:443"

  mongo:
    depends_on:
      - product-service
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  mongo-express:
    depends_on:
      - mongo
    image: mongo-express
    restart: always
    ports:
      - 8082:8082
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
