version: "3.1"

services:
  product-service:
    build:
      context: ../src/
      dockerfile: Dockerfile

  mongo:
    image: mongo

  mongo-express:
    depends_on:
      - mongo
    image: mongo-express
    restart: always
